### ISSUE TITLE
cdn引用的swagger失效

### ISSUE THREAD

**Issue by caizhichao** [hyperf/swagger#12]
GET https://unpkg.hyperf.wiki/swagger-ui-dist@4.5.0/swagger-ui.css net::ERR_CONNECTION_RESET了解此错误AI
swagger:15 

 GET https://unpkg.hyperf.wiki/swagger-ui-dist@4.5.0/swagger-ui-bundle.js net::ERR_CONNECTION_RESET了解此错误AI
swagger:16 

 GET https://unpkg.hyperf.wiki/swagger-ui-dist@4.5.0/swagger-ui-standalone-preset.js net::ERR_CONNECTION_RESET了解此错误AI
swagger:19 Uncaught ReferenceError: SwaggerUIBundle is not defined
    at window.onload (swagger:19:7)

**Comment by limingxinleo** [comment]
https://hyperf.wiki/3.1/#/zh-cn/swagger?id=%e6%9b%bf%e6%8d%a2-swagger-%e9%9d%a2%e6%9d%bf

**Comment by caizhichao** [comment]
好的 感谢
