### ISSUE TITLE
这个怎么用呀

### ISSUE THREAD

**Issue by skboy** [hyperf/swagger#2]
没说明不知道怎么使用呀

**Comment by MalongGuo** [comment]
php bin/hyperf.php swagger:gen 用这个命令，然后你再看哈它的几个依赖包的用法，你都清楚它的原理了...

**Comment by yinyutaoyyt** [comment]
老哥 会用了吗

**Comment by zcstation** [comment]
使用方法看这里 [https://zircote.github.io/swagger-php/guide/](https://zircote.github.io/swagger-php/guide/)

**Comment by Greatfar** [comment]
连个README.md文档都没有的

**Comment by limingxinleo** [comment]
实用性不太好，所以是个半成品，不推荐用
