### ISSUE TITLE
请问提示unknown socket type [0] 是怎么回事啊

### ISSUE THREAD

**Issue by Lazybin** [hyperf/swagger#7]
![image](https://user-images.githubusercontent.com/2576969/219541525-b1930a2a-38fe-4751-86fa-827305227579.png)

**Comment by bizvip** [comment]
你到bootSwaggerListener那个监听文件，在配置里面加一行 'sock_type'=>SWOOLE_SOCK_TCP, 就可以了，他这里少了个参数，默认参数0，所以socket type不支持。
