### ISSUE TITLE
css,js文件421，访问不了

### ISSUE THREAD

**Issue by xycczZ** [hyperf/swagger#9]
swagger网页上的几个css,js文件都是421，访问不了
<img width="800" alt="image" src="https://github.com/hyperf/swagger/assets/23651075/0e8751c1-c793-4950-b6c5-b9c4f97b6b81">
持续了至少一个月了

**Comment by limingxinleo** [comment]
https://hyperf.wiki/3.1/#/zh-cn/swagger?id=%e6%9b%bf%e6%8d%a2-swagger-%e9%9d%a2%e6%9d%bf

**Comment by xycczZ** [comment]
谢谢你的极速回复，我已经按照文档上的修改了html配置了。
